application: voicebox-sandwich
version: 1
runtime: python
api_version: 1

handlers:

- url: /(.*\.(gif|png|jpg|ico|js|css|php|xml))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|php|xml))

- url: /stylesheets
  static_dir: stylesheets
  
- url: /dailyreport
  script: report.py
  login: admin

- url: /receipt
  script: receipt.py
  login: admin

- url: /.*
  script: vbsandwich.py

